//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSYS_PPG_LPS_ProxyConnector.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionManager.IBSExternalParameter", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.SqlDataType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.DbType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.MappingField[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.MappingField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.PrintLogInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.PrintLogInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.TabelProperties[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.TabelProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.SystemOptionsByteArrayInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.ServerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.DatabaseInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.ScriptInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.ScriptInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.ColumnInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.ColumnInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.ForeignKeyInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.ForeignKeyInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.SqlToolsDatabaseToolsScriptInfoType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.IndexOptimizationSuggestion[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCSYS_PPG_LPS_ProxyConnector.DataService.IndexOptimizationSuggestion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class IBSExternalParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DbType DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmpytIsNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DbType DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((this.DataTypeField.Equals(value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmpytIsNull {
            get {
                return this.EmpytIsNullField;
            }
            set {
                if ((this.EmpytIsNullField.Equals(value) != true)) {
                    this.EmpytIsNullField = value;
                    this.RaisePropertyChanged("EmpytIsNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlDataType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Dac.Model")]
    public enum SqlDataType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BigInt = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmallInt = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TinyInt = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bit = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decimal = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Numeric = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Money = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmallMoney = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Float = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Real = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmallDateTime = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Char = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VarChar = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NChar = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NVarChar = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NText = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Binary = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VarBinary = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cursor = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Variant = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Table = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timestamp = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UniqueIdentifier = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Xml = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Date = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Time = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime2 = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTimeOffset = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rowversion = 33,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionManager.DataProvider", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    public enum DataProvider : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MSSQL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MSACCESS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ORACLE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MYSQL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OLEDB = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ODBC = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MappingField", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class MappingField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationFieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceFileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationFieldName {
            get {
                return this.DestinationFieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationFieldNameField, value) != true)) {
                    this.DestinationFieldNameField = value;
                    this.RaisePropertyChanged("DestinationFieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceFileName {
            get {
                return this.SourceFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceFileNameField, value) != true)) {
                    this.SourceFileNameField = value;
                    this.RaisePropertyChanged("SourceFileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintLogInfo", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class PrintLogInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWarningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogActivityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LogDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunctionName {
            get {
                return this.FunctionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionNameField, value) != true)) {
                    this.FunctionNameField = value;
                    this.RaisePropertyChanged("FunctionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinished {
            get {
                return this.IsFinishedField;
            }
            set {
                if ((this.IsFinishedField.Equals(value) != true)) {
                    this.IsFinishedField = value;
                    this.RaisePropertyChanged("IsFinished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWarning {
            get {
                return this.IsWarningField;
            }
            set {
                if ((this.IsWarningField.Equals(value) != true)) {
                    this.IsWarningField = value;
                    this.RaisePropertyChanged("IsWarning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogActivityType {
            get {
                return this.LogActivityTypeField;
            }
            set {
                if ((this.LogActivityTypeField.Equals(value) != true)) {
                    this.LogActivityTypeField = value;
                    this.RaisePropertyChanged("LogActivityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LogDateTime {
            get {
                return this.LogDateTimeField;
            }
            set {
                if ((this.LogDateTimeField.Equals(value) != true)) {
                    this.LogDateTimeField = value;
                    this.RaisePropertyChanged("LogDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogText {
            get {
                return this.LogTextField;
            }
            set {
                if ((object.ReferenceEquals(this.LogTextField, value) != true)) {
                    this.LogTextField = value;
                    this.RaisePropertyChanged("LogText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TabelProperties", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class TabelProperties : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PCSYS_PPG_LPS_ProxyConnector.DataService.SqlDataType DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCSYS_PPG_LPS_ProxyConnector.DataService.SqlDataType DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((this.DataTypeField.Equals(value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemOptions.ByteArrayInfo", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class SystemOptionsByteArrayInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ByteArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ByteArray {
            get {
                return this.ByteArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.ByteArrayField, value) != true)) {
                    this.ByteArrayField = value;
                    this.RaisePropertyChanged("ByteArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerInfo", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class ServerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PCSYS_PPG_LPS_ProxyConnector.DataService.DatabaseInfo DatabaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PCSYS_PPG_LPS_ProxyConnector.DataService.ScriptInfo[] ScriptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collation {
            get {
                return this.CollationField;
            }
            set {
                if ((object.ReferenceEquals(this.CollationField, value) != true)) {
                    this.CollationField = value;
                    this.RaisePropertyChanged("Collation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCSYS_PPG_LPS_ProxyConnector.DataService.DatabaseInfo Database {
            get {
                return this.DatabaseField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseField, value) != true)) {
                    this.DatabaseField = value;
                    this.RaisePropertyChanged("Database");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCSYS_PPG_LPS_ProxyConnector.DataService.ScriptInfo[] Scripts {
            get {
                return this.ScriptsField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptsField, value) != true)) {
                    this.ScriptsField = value;
                    this.RaisePropertyChanged("Scripts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseInfo", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class DatabaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collation {
            get {
                return this.CollationField;
            }
            set {
                if ((object.ReferenceEquals(this.CollationField, value) != true)) {
                    this.CollationField = value;
                    this.RaisePropertyChanged("Collation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScriptInfo", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class ScriptInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PCSYS_PPG_LPS_ProxyConnector.DataService.ColumnInfo[] ColumnsInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PCSYS_PPG_LPS_ProxyConnector.DataService.ForeignKeyInfo[] KeysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PCSYS_PPG_LPS_ProxyConnector.DataService.SqlToolsDatabaseToolsScriptInfoType ScriptTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCSYS_PPG_LPS_ProxyConnector.DataService.ColumnInfo[] ColumnsInfo {
            get {
                return this.ColumnsInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsInfoField, value) != true)) {
                    this.ColumnsInfoField = value;
                    this.RaisePropertyChanged("ColumnsInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCSYS_PPG_LPS_ProxyConnector.DataService.ForeignKeyInfo[] Keys {
            get {
                return this.KeysField;
            }
            set {
                if ((object.ReferenceEquals(this.KeysField, value) != true)) {
                    this.KeysField = value;
                    this.RaisePropertyChanged("Keys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Script {
            get {
                return this.ScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptField, value) != true)) {
                    this.ScriptField = value;
                    this.RaisePropertyChanged("Script");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCSYS_PPG_LPS_ProxyConnector.DataService.SqlToolsDatabaseToolsScriptInfoType ScriptType {
            get {
                return this.ScriptTypeField;
            }
            set {
                if ((this.ScriptTypeField.Equals(value) != true)) {
                    this.ScriptTypeField = value;
                    this.RaisePropertyChanged("ScriptType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColumnInfo", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class ColumnInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsForeignKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrimaryKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NullsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataLength {
            get {
                return this.DataLengthField;
            }
            set {
                if ((this.DataLengthField.Equals(value) != true)) {
                    this.DataLengthField = value;
                    this.RaisePropertyChanged("DataLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTypeField, value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultField, value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForeignKey {
            get {
                return this.IsForeignKeyField;
            }
            set {
                if ((this.IsForeignKeyField.Equals(value) != true)) {
                    this.IsForeignKeyField = value;
                    this.RaisePropertyChanged("IsForeignKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsIdentity {
            get {
                return this.IsIdentityField;
            }
            set {
                if ((this.IsIdentityField.Equals(value) != true)) {
                    this.IsIdentityField = value;
                    this.RaisePropertyChanged("IsIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrimaryKey {
            get {
                return this.IsPrimaryKeyField;
            }
            set {
                if ((this.IsPrimaryKeyField.Equals(value) != true)) {
                    this.IsPrimaryKeyField = value;
                    this.RaisePropertyChanged("IsPrimaryKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Nulls {
            get {
                return this.NullsField;
            }
            set {
                if ((this.NullsField.Equals(value) != true)) {
                    this.NullsField = value;
                    this.RaisePropertyChanged("Nulls");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignKeyInfo", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    [System.SerializableAttribute()]
    public partial class ForeignKeyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferencedKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferencedTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferencedKey {
            get {
                return this.ReferencedKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencedKeyField, value) != true)) {
                    this.ReferencedKeyField = value;
                    this.RaisePropertyChanged("ReferencedKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferencedTable {
            get {
                return this.ReferencedTableField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencedTableField, value) != true)) {
                    this.ReferencedTableField = value;
                    this.RaisePropertyChanged("ReferencedTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlTools.DatabaseTools.ScriptInfoType", Namespace="http://schemas.datacontract.org/2004/07/IBS_Data_Service_4.DataServer")]
    public enum SqlToolsDatabaseToolsScriptInfoType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Table = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        View = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndexOptimizationSuggestion", Namespace="http://schemas.datacontract.org/2004/07/IBS_PrintService_Admin.Code.Data")]
    [System.SerializableAttribute()]
    public partial class IndexOptimizationSuggestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuggestedIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuggestedIndex {
            get {
                return this.SuggestedIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.SuggestedIndexField, value) != true)) {
                    this.SuggestedIndexField = value;
                    this.RaisePropertyChanged("SuggestedIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IAppService")]
    public interface IAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetData", ReplyAction="http://tempuri.org/IAppService/GetDataResponse")]
        System.Data.DataSet GetData(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetData", ReplyAction="http://tempuri.org/IAppService/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ServiceTest", ReplyAction="http://tempuri.org/IAppService/ServiceTestResponse")]
        string ServiceTest(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ServiceTest", ReplyAction="http://tempuri.org/IAppService/ServiceTestResponse")]
        System.Threading.Tasks.Task<string> ServiceTestAsync(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetDataWithParameters", ReplyAction="http://tempuri.org/IAppService/GetDataWithParametersResponse")]
        System.Data.DataSet GetDataWithParameters(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetDataWithParameters", ReplyAction="http://tempuri.org/IAppService/GetDataWithParametersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataWithParametersAsync(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetDataByStoredProcedure", ReplyAction="http://tempuri.org/IAppService/GetDataByStoredProcedureResponse")]
        System.Data.DataSet GetDataByStoredProcedure(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetDataByStoredProcedure", ReplyAction="http://tempuri.org/IAppService/GetDataByStoredProcedureResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataByStoredProcedureAsync(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/RestartDataService", ReplyAction="http://tempuri.org/IAppService/RestartDataServiceResponse")]
        void RestartDataService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/RestartDataService", ReplyAction="http://tempuri.org/IAppService/RestartDataServiceResponse")]
        System.Threading.Tasks.Task RestartDataServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetConnectionString", ReplyAction="http://tempuri.org/IAppService/GetConnectionStringResponse")]
        string GetConnectionString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetConnectionString", ReplyAction="http://tempuri.org/IAppService/GetConnectionStringResponse")]
        System.Threading.Tasks.Task<string> GetConnectionStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetDataOut", ReplyAction="http://tempuri.org/IAppService/GetDataOutResponse")]
        System.Data.DataSet GetDataOut(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetDataOut", ReplyAction="http://tempuri.org/IAppService/GetDataOutResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataOutAsync(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/SaveData", ReplyAction="http://tempuri.org/IAppService/SaveDataResponse")]
        int SaveData(System.Data.DataSet input, string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/SaveData", ReplyAction="http://tempuri.org/IAppService/SaveDataResponse")]
        System.Threading.Tasks.Task<int> SaveDataAsync(System.Data.DataSet input, string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteScalarInt", ReplyAction="http://tempuri.org/IAppService/ExecuteScalarIntResponse")]
        int ExecuteScalarInt(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteScalarInt", ReplyAction="http://tempuri.org/IAppService/ExecuteScalarIntResponse")]
        System.Threading.Tasks.Task<int> ExecuteScalarIntAsync(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteScalarString", ReplyAction="http://tempuri.org/IAppService/ExecuteScalarStringResponse")]
        string ExecuteScalarString(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteScalarString", ReplyAction="http://tempuri.org/IAppService/ExecuteScalarStringResponse")]
        System.Threading.Tasks.Task<string> ExecuteScalarStringAsync(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IAppService/ExecuteNonQueryResponse")]
        int ExecuteNonQuery(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IAppService/ExecuteNonQueryResponse")]
        System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/CheckConnection", ReplyAction="http://tempuri.org/IAppService/CheckConnectionResponse")]
        string CheckConnection(string clientAdress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/CheckConnection", ReplyAction="http://tempuri.org/IAppService/CheckConnectionResponse")]
        System.Threading.Tasks.Task<string> CheckConnectionAsync(string clientAdress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ConnectionIsAlive", ReplyAction="http://tempuri.org/IAppService/ConnectionIsAliveResponse")]
        bool ConnectionIsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ConnectionIsAlive", ReplyAction="http://tempuri.org/IAppService/ConnectionIsAliveResponse")]
        System.Threading.Tasks.Task<bool> ConnectionIsAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetUserLogins", ReplyAction="http://tempuri.org/IAppService/GetUserLoginsResponse")]
        System.Data.DataSet GetUserLogins(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetUserLogins", ReplyAction="http://tempuri.org/IAppService/GetUserLoginsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserLoginsAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetPrintQueueInfo", ReplyAction="http://tempuri.org/IAppService/GetPrintQueueInfoResponse")]
        System.Data.DataTable GetPrintQueueInfo(System.Data.DataTable profileIds, int holded);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetPrintQueueInfo", ReplyAction="http://tempuri.org/IAppService/GetPrintQueueInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPrintQueueInfoAsync(System.Data.DataTable profileIds, int holded);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/SaveDocument", ReplyAction="http://tempuri.org/IAppService/SaveDocumentResponse")]
        int SaveDocument(string sqlString, byte[] images);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/SaveDocument", ReplyAction="http://tempuri.org/IAppService/SaveDocumentResponse")]
        System.Threading.Tasks.Task<int> SaveDocumentAsync(string sqlString, byte[] images);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/SaveUniCodeText", ReplyAction="http://tempuri.org/IAppService/SaveUniCodeTextResponse")]
        int SaveUniCodeText(string sqlString, string labelText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/SaveUniCodeText", ReplyAction="http://tempuri.org/IAppService/SaveUniCodeTextResponse")]
        System.Threading.Tasks.Task<int> SaveUniCodeTextAsync(string sqlString, string labelText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetDataForDataVariable", ReplyAction="http://tempuri.org/IAppService/GetDataForDataVariableResponse")]
        System.Data.DataSet GetDataForDataVariable(string dataVariable, string connectionstring, int provider, bool allowEmpty, bool allowNull);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetDataForDataVariable", ReplyAction="http://tempuri.org/IAppService/GetDataForDataVariableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataForDataVariableAsync(string dataVariable, string connectionstring, int provider, bool allowEmpty, bool allowNull);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteExternalDataWithParameters", ReplyAction="http://tempuri.org/IAppService/ExecuteExternalDataWithParametersResponse")]
        void ExecuteExternalDataWithParameters(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteExternalDataWithParameters", ReplyAction="http://tempuri.org/IAppService/ExecuteExternalDataWithParametersResponse")]
        System.Threading.Tasks.Task ExecuteExternalDataWithParametersAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/WriteToDatabaseLog", ReplyAction="http://tempuri.org/IAppService/WriteToDatabaseLogResponse")]
        void WriteToDatabaseLog(string clientName, string logText, bool isError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/WriteToDatabaseLog", ReplyAction="http://tempuri.org/IAppService/WriteToDatabaseLogResponse")]
        System.Threading.Tasks.Task WriteToDatabaseLogAsync(string clientName, string logText, bool isError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/WriteToDatabaseLogServiceName", ReplyAction="http://tempuri.org/IAppService/WriteToDatabaseLogServiceNameResponse")]
        void WriteToDatabaseLogServiceName(string clientName, string logText, bool isError, string serviceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/WriteToDatabaseLogServiceName", ReplyAction="http://tempuri.org/IAppService/WriteToDatabaseLogServiceNameResponse")]
        System.Threading.Tasks.Task WriteToDatabaseLogServiceNameAsync(string clientName, string logText, bool isError, string serviceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/SqlCopyBulk", ReplyAction="http://tempuri.org/IAppService/SqlCopyBulkResponse")]
        string SqlCopyBulk(System.Data.DataTable dt, string connectionString, PCSYS_PPG_LPS_ProxyConnector.DataService.MappingField[] fields, string destinationTableName, bool keepIdentity, bool keepNulls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/SqlCopyBulk", ReplyAction="http://tempuri.org/IAppService/SqlCopyBulkResponse")]
        System.Threading.Tasks.Task<string> SqlCopyBulkAsync(System.Data.DataTable dt, string connectionString, PCSYS_PPG_LPS_ProxyConnector.DataService.MappingField[] fields, string destinationTableName, bool keepIdentity, bool keepNulls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetTabels", ReplyAction="http://tempuri.org/IAppService/GetTabelsResponse")]
        System.Data.DataTable GetTabels(string dataSourceString, int provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetTabels", ReplyAction="http://tempuri.org/IAppService/GetTabelsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTabelsAsync(string dataSourceString, int provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalScalarInt", ReplyAction="http://tempuri.org/IAppService/GetExternalScalarIntResponse")]
        int GetExternalScalarInt(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalScalarInt", ReplyAction="http://tempuri.org/IAppService/GetExternalScalarIntResponse")]
        System.Threading.Tasks.Task<int> GetExternalScalarIntAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/InsertQuery", ReplyAction="http://tempuri.org/IAppService/InsertQueryResponse")]
        void InsertQuery(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string insertQueryText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/InsertQuery", ReplyAction="http://tempuri.org/IAppService/InsertQueryResponse")]
        System.Threading.Tasks.Task InsertQueryAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string insertQueryText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/InsertQuiries", ReplyAction="http://tempuri.org/IAppService/InsertQuiriesResponse")]
        void InsertQuiries(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, System.Data.DataTable insertQuiriesRows, bool inTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/InsertQuiries", ReplyAction="http://tempuri.org/IAppService/InsertQuiriesResponse")]
        System.Threading.Tasks.Task InsertQuiriesAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, System.Data.DataTable insertQuiriesRows, bool inTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalData", ReplyAction="http://tempuri.org/IAppService/GetExternalDataResponse")]
        System.Data.DataSet GetExternalData(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, bool allowEmpty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalData", ReplyAction="http://tempuri.org/IAppService/GetExternalDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetExternalDataAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, bool allowEmpty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalDataWithParameters", ReplyAction="http://tempuri.org/IAppService/GetExternalDataWithParametersResponse")]
        System.Data.DataSet GetExternalDataWithParameters(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters, bool allowEmpty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalDataWithParameters", ReplyAction="http://tempuri.org/IAppService/GetExternalDataWithParametersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetExternalDataWithParametersAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters, bool allowEmpty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalDataByConnectionId", ReplyAction="http://tempuri.org/IAppService/GetExternalDataByConnectionIdResponse")]
        System.Data.DataSet GetExternalDataByConnectionId(int connectionId, string sqlString, bool allowEmpty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalDataByConnectionId", ReplyAction="http://tempuri.org/IAppService/GetExternalDataByConnectionIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetExternalDataByConnectionIdAsync(int connectionId, string sqlString, bool allowEmpty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalDataByParametersByConnectionId", ReplyAction="http://tempuri.org/IAppService/GetExternalDataByParametersByConnectionIdResponse")]
        System.Data.DataSet GetExternalDataByParametersByConnectionId(int connectionId, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parms, bool allowEmpty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalDataByParametersByConnectionId", ReplyAction="http://tempuri.org/IAppService/GetExternalDataByParametersByConnectionIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetExternalDataByParametersByConnectionIdAsync(int connectionId, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parms, bool allowEmpty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/InsertPrintLog", ReplyAction="http://tempuri.org/IAppService/InsertPrintLogResponse")]
        void InsertPrintLog(PCSYS_PPG_LPS_ProxyConnector.DataService.PrintLogInfo[] logs, int printid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/InsertPrintLog", ReplyAction="http://tempuri.org/IAppService/InsertPrintLogResponse")]
        System.Threading.Tasks.Task InsertPrintLogAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.PrintLogInfo[] logs, int printid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteNonQueryWithParameters", ReplyAction="http://tempuri.org/IAppService/ExecuteNonQueryWithParametersResponse")]
        int ExecuteNonQueryWithParameters(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteNonQueryWithParameters", ReplyAction="http://tempuri.org/IAppService/ExecuteNonQueryWithParametersResponse")]
        System.Threading.Tasks.Task<int> ExecuteNonQueryWithParametersAsync(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteScalarStringWithParameters", ReplyAction="http://tempuri.org/IAppService/ExecuteScalarStringWithParametersResponse")]
        string ExecuteScalarStringWithParameters(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/ExecuteScalarStringWithParameters", ReplyAction="http://tempuri.org/IAppService/ExecuteScalarStringWithParametersResponse")]
        System.Threading.Tasks.Task<string> ExecuteScalarStringWithParametersAsync(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetTabelProperties", ReplyAction="http://tempuri.org/IAppService/GetTabelPropertiesResponse")]
        PCSYS_PPG_LPS_ProxyConnector.DataService.TabelProperties[] GetTabelProperties(string sqlString, int connectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetTabelProperties", ReplyAction="http://tempuri.org/IAppService/GetTabelPropertiesResponse")]
        System.Threading.Tasks.Task<PCSYS_PPG_LPS_ProxyConnector.DataService.TabelProperties[]> GetTabelPropertiesAsync(string sqlString, int connectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalScalarString", ReplyAction="http://tempuri.org/IAppService/GetExternalScalarStringResponse")]
        string GetExternalScalarString(int provider, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetExternalScalarString", ReplyAction="http://tempuri.org/IAppService/GetExternalScalarStringResponse")]
        System.Threading.Tasks.Task<string> GetExternalScalarStringAsync(int provider, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetBytes", ReplyAction="http://tempuri.org/IAppService/GetBytesResponse")]
        PCSYS_PPG_LPS_ProxyConnector.DataService.SystemOptionsByteArrayInfo GetBytes(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetBytes", ReplyAction="http://tempuri.org/IAppService/GetBytesResponse")]
        System.Threading.Tasks.Task<PCSYS_PPG_LPS_ProxyConnector.DataService.SystemOptionsByteArrayInfo> GetBytesAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetScriptDatabase", ReplyAction="http://tempuri.org/IAppService/GetScriptDatabaseResponse")]
        PCSYS_PPG_LPS_ProxyConnector.DataService.ServerInfo GetScriptDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetScriptDatabase", ReplyAction="http://tempuri.org/IAppService/GetScriptDatabaseResponse")]
        System.Threading.Tasks.Task<PCSYS_PPG_LPS_ProxyConnector.DataService.ServerInfo> GetScriptDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetSchemas", ReplyAction="http://tempuri.org/IAppService/GetSchemasResponse")]
        System.Data.DataSet GetSchemas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetSchemas", ReplyAction="http://tempuri.org/IAppService/GetSchemasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSchemasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetCurrentDatabaseInfo", ReplyAction="http://tempuri.org/IAppService/GetCurrentDatabaseInfoResponse")]
        string GetCurrentDatabaseInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetCurrentDatabaseInfo", ReplyAction="http://tempuri.org/IAppService/GetCurrentDatabaseInfoResponse")]
        System.Threading.Tasks.Task<string> GetCurrentDatabaseInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/TestExternalConnection", ReplyAction="http://tempuri.org/IAppService/TestExternalConnectionResponse")]
        bool TestExternalConnection(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/TestExternalConnection", ReplyAction="http://tempuri.org/IAppService/TestExternalConnectionResponse")]
        System.Threading.Tasks.Task<bool> TestExternalConnectionAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetIndexOptimizationSuggestions", ReplyAction="http://tempuri.org/IAppService/GetIndexOptimizationSuggestionsResponse")]
        PCSYS_PPG_LPS_ProxyConnector.DataService.IndexOptimizationSuggestion[] GetIndexOptimizationSuggestions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/GetIndexOptimizationSuggestions", ReplyAction="http://tempuri.org/IAppService/GetIndexOptimizationSuggestionsResponse")]
        System.Threading.Tasks.Task<PCSYS_PPG_LPS_ProxyConnector.DataService.IndexOptimizationSuggestion[]> GetIndexOptimizationSuggestionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppServiceChannel : PCSYS_PPG_LPS_ProxyConnector.DataService.IAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppServiceClient : System.ServiceModel.ClientBase<PCSYS_PPG_LPS_ProxyConnector.DataService.IAppService>, PCSYS_PPG_LPS_ProxyConnector.DataService.IAppService {
        
        public AppServiceClient() {
        }
        
        public AppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetData(string sqlString) {
            return base.Channel.GetData(sqlString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string sqlString) {
            return base.Channel.GetDataAsync(sqlString);
        }
        
        public string ServiceTest(string client) {
            return base.Channel.ServiceTest(client);
        }
        
        public System.Threading.Tasks.Task<string> ServiceTestAsync(string client) {
            return base.Channel.ServiceTestAsync(client);
        }
        
        public System.Data.DataSet GetDataWithParameters(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.GetDataWithParameters(sqlString, parameters);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataWithParametersAsync(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.GetDataWithParametersAsync(sqlString, parameters);
        }
        
        public System.Data.DataSet GetDataByStoredProcedure(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.GetDataByStoredProcedure(sqlString, parameters);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataByStoredProcedureAsync(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.GetDataByStoredProcedureAsync(sqlString, parameters);
        }
        
        public void RestartDataService() {
            base.Channel.RestartDataService();
        }
        
        public System.Threading.Tasks.Task RestartDataServiceAsync() {
            return base.Channel.RestartDataServiceAsync();
        }
        
        public string GetConnectionString() {
            return base.Channel.GetConnectionString();
        }
        
        public System.Threading.Tasks.Task<string> GetConnectionStringAsync() {
            return base.Channel.GetConnectionStringAsync();
        }
        
        public System.Data.DataSet GetDataOut(string sqlString) {
            return base.Channel.GetDataOut(sqlString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataOutAsync(string sqlString) {
            return base.Channel.GetDataOutAsync(sqlString);
        }
        
        public int SaveData(System.Data.DataSet input, string sqlString) {
            return base.Channel.SaveData(input, sqlString);
        }
        
        public System.Threading.Tasks.Task<int> SaveDataAsync(System.Data.DataSet input, string sqlString) {
            return base.Channel.SaveDataAsync(input, sqlString);
        }
        
        public int ExecuteScalarInt(string sqlString) {
            return base.Channel.ExecuteScalarInt(sqlString);
        }
        
        public System.Threading.Tasks.Task<int> ExecuteScalarIntAsync(string sqlString) {
            return base.Channel.ExecuteScalarIntAsync(sqlString);
        }
        
        public string ExecuteScalarString(string sqlString) {
            return base.Channel.ExecuteScalarString(sqlString);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteScalarStringAsync(string sqlString) {
            return base.Channel.ExecuteScalarStringAsync(sqlString);
        }
        
        public int ExecuteNonQuery(string sqlString) {
            return base.Channel.ExecuteNonQuery(sqlString);
        }
        
        public System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string sqlString) {
            return base.Channel.ExecuteNonQueryAsync(sqlString);
        }
        
        public string CheckConnection(string clientAdress) {
            return base.Channel.CheckConnection(clientAdress);
        }
        
        public System.Threading.Tasks.Task<string> CheckConnectionAsync(string clientAdress) {
            return base.Channel.CheckConnectionAsync(clientAdress);
        }
        
        public bool ConnectionIsAlive() {
            return base.Channel.ConnectionIsAlive();
        }
        
        public System.Threading.Tasks.Task<bool> ConnectionIsAliveAsync() {
            return base.Channel.ConnectionIsAliveAsync();
        }
        
        public System.Data.DataSet GetUserLogins(string userName, string password) {
            return base.Channel.GetUserLogins(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserLoginsAsync(string userName, string password) {
            return base.Channel.GetUserLoginsAsync(userName, password);
        }
        
        public System.Data.DataTable GetPrintQueueInfo(System.Data.DataTable profileIds, int holded) {
            return base.Channel.GetPrintQueueInfo(profileIds, holded);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPrintQueueInfoAsync(System.Data.DataTable profileIds, int holded) {
            return base.Channel.GetPrintQueueInfoAsync(profileIds, holded);
        }
        
        public int SaveDocument(string sqlString, byte[] images) {
            return base.Channel.SaveDocument(sqlString, images);
        }
        
        public System.Threading.Tasks.Task<int> SaveDocumentAsync(string sqlString, byte[] images) {
            return base.Channel.SaveDocumentAsync(sqlString, images);
        }
        
        public int SaveUniCodeText(string sqlString, string labelText) {
            return base.Channel.SaveUniCodeText(sqlString, labelText);
        }
        
        public System.Threading.Tasks.Task<int> SaveUniCodeTextAsync(string sqlString, string labelText) {
            return base.Channel.SaveUniCodeTextAsync(sqlString, labelText);
        }
        
        public System.Data.DataSet GetDataForDataVariable(string dataVariable, string connectionstring, int provider, bool allowEmpty, bool allowNull) {
            return base.Channel.GetDataForDataVariable(dataVariable, connectionstring, provider, allowEmpty, allowNull);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataForDataVariableAsync(string dataVariable, string connectionstring, int provider, bool allowEmpty, bool allowNull) {
            return base.Channel.GetDataForDataVariableAsync(dataVariable, connectionstring, provider, allowEmpty, allowNull);
        }
        
        public void ExecuteExternalDataWithParameters(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            base.Channel.ExecuteExternalDataWithParameters(provider, connectionstring, sqlString, parameters);
        }
        
        public System.Threading.Tasks.Task ExecuteExternalDataWithParametersAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.ExecuteExternalDataWithParametersAsync(provider, connectionstring, sqlString, parameters);
        }
        
        public void WriteToDatabaseLog(string clientName, string logText, bool isError) {
            base.Channel.WriteToDatabaseLog(clientName, logText, isError);
        }
        
        public System.Threading.Tasks.Task WriteToDatabaseLogAsync(string clientName, string logText, bool isError) {
            return base.Channel.WriteToDatabaseLogAsync(clientName, logText, isError);
        }
        
        public void WriteToDatabaseLogServiceName(string clientName, string logText, bool isError, string serviceName) {
            base.Channel.WriteToDatabaseLogServiceName(clientName, logText, isError, serviceName);
        }
        
        public System.Threading.Tasks.Task WriteToDatabaseLogServiceNameAsync(string clientName, string logText, bool isError, string serviceName) {
            return base.Channel.WriteToDatabaseLogServiceNameAsync(clientName, logText, isError, serviceName);
        }
        
        public string SqlCopyBulk(System.Data.DataTable dt, string connectionString, PCSYS_PPG_LPS_ProxyConnector.DataService.MappingField[] fields, string destinationTableName, bool keepIdentity, bool keepNulls) {
            return base.Channel.SqlCopyBulk(dt, connectionString, fields, destinationTableName, keepIdentity, keepNulls);
        }
        
        public System.Threading.Tasks.Task<string> SqlCopyBulkAsync(System.Data.DataTable dt, string connectionString, PCSYS_PPG_LPS_ProxyConnector.DataService.MappingField[] fields, string destinationTableName, bool keepIdentity, bool keepNulls) {
            return base.Channel.SqlCopyBulkAsync(dt, connectionString, fields, destinationTableName, keepIdentity, keepNulls);
        }
        
        public System.Data.DataTable GetTabels(string dataSourceString, int provider) {
            return base.Channel.GetTabels(dataSourceString, provider);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTabelsAsync(string dataSourceString, int provider) {
            return base.Channel.GetTabelsAsync(dataSourceString, provider);
        }
        
        public int GetExternalScalarInt(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString) {
            return base.Channel.GetExternalScalarInt(provider, connectionstring, sqlString);
        }
        
        public System.Threading.Tasks.Task<int> GetExternalScalarIntAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString) {
            return base.Channel.GetExternalScalarIntAsync(provider, connectionstring, sqlString);
        }
        
        public void InsertQuery(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string insertQueryText) {
            base.Channel.InsertQuery(provider, connectionstring, insertQueryText);
        }
        
        public System.Threading.Tasks.Task InsertQueryAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string insertQueryText) {
            return base.Channel.InsertQueryAsync(provider, connectionstring, insertQueryText);
        }
        
        public void InsertQuiries(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, System.Data.DataTable insertQuiriesRows, bool inTransaction) {
            base.Channel.InsertQuiries(provider, connectionstring, insertQuiriesRows, inTransaction);
        }
        
        public System.Threading.Tasks.Task InsertQuiriesAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, System.Data.DataTable insertQuiriesRows, bool inTransaction) {
            return base.Channel.InsertQuiriesAsync(provider, connectionstring, insertQuiriesRows, inTransaction);
        }
        
        public System.Data.DataSet GetExternalData(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, bool allowEmpty) {
            return base.Channel.GetExternalData(provider, connectionstring, sqlString, allowEmpty);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetExternalDataAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, bool allowEmpty) {
            return base.Channel.GetExternalDataAsync(provider, connectionstring, sqlString, allowEmpty);
        }
        
        public System.Data.DataSet GetExternalDataWithParameters(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters, bool allowEmpty) {
            return base.Channel.GetExternalDataWithParameters(provider, connectionstring, sqlString, parameters, allowEmpty);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetExternalDataWithParametersAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters, bool allowEmpty) {
            return base.Channel.GetExternalDataWithParametersAsync(provider, connectionstring, sqlString, parameters, allowEmpty);
        }
        
        public System.Data.DataSet GetExternalDataByConnectionId(int connectionId, string sqlString, bool allowEmpty) {
            return base.Channel.GetExternalDataByConnectionId(connectionId, sqlString, allowEmpty);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetExternalDataByConnectionIdAsync(int connectionId, string sqlString, bool allowEmpty) {
            return base.Channel.GetExternalDataByConnectionIdAsync(connectionId, sqlString, allowEmpty);
        }
        
        public System.Data.DataSet GetExternalDataByParametersByConnectionId(int connectionId, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parms, bool allowEmpty) {
            return base.Channel.GetExternalDataByParametersByConnectionId(connectionId, sqlString, parms, allowEmpty);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetExternalDataByParametersByConnectionIdAsync(int connectionId, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parms, bool allowEmpty) {
            return base.Channel.GetExternalDataByParametersByConnectionIdAsync(connectionId, sqlString, parms, allowEmpty);
        }
        
        public void InsertPrintLog(PCSYS_PPG_LPS_ProxyConnector.DataService.PrintLogInfo[] logs, int printid) {
            base.Channel.InsertPrintLog(logs, printid);
        }
        
        public System.Threading.Tasks.Task InsertPrintLogAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.PrintLogInfo[] logs, int printid) {
            return base.Channel.InsertPrintLogAsync(logs, printid);
        }
        
        public int ExecuteNonQueryWithParameters(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.ExecuteNonQueryWithParameters(sqlString, parameters);
        }
        
        public System.Threading.Tasks.Task<int> ExecuteNonQueryWithParametersAsync(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.ExecuteNonQueryWithParametersAsync(sqlString, parameters);
        }
        
        public string ExecuteScalarStringWithParameters(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.ExecuteScalarStringWithParameters(sqlString, parameters);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteScalarStringWithParametersAsync(string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.ExecuteScalarStringWithParametersAsync(sqlString, parameters);
        }
        
        public PCSYS_PPG_LPS_ProxyConnector.DataService.TabelProperties[] GetTabelProperties(string sqlString, int connectionId) {
            return base.Channel.GetTabelProperties(sqlString, connectionId);
        }
        
        public System.Threading.Tasks.Task<PCSYS_PPG_LPS_ProxyConnector.DataService.TabelProperties[]> GetTabelPropertiesAsync(string sqlString, int connectionId) {
            return base.Channel.GetTabelPropertiesAsync(sqlString, connectionId);
        }
        
        public string GetExternalScalarString(int provider, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parms) {
            return base.Channel.GetExternalScalarString(provider, sqlString, parms);
        }
        
        public System.Threading.Tasks.Task<string> GetExternalScalarStringAsync(int provider, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parms) {
            return base.Channel.GetExternalScalarStringAsync(provider, sqlString, parms);
        }
        
        public PCSYS_PPG_LPS_ProxyConnector.DataService.SystemOptionsByteArrayInfo GetBytes(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.GetBytes(provider, connectionstring, sqlString, parameters);
        }
        
        public System.Threading.Tasks.Task<PCSYS_PPG_LPS_ProxyConnector.DataService.SystemOptionsByteArrayInfo> GetBytesAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionstring, string sqlString, PCSYS_PPG_LPS_ProxyConnector.DataService.IBSExternalParameter[] parameters) {
            return base.Channel.GetBytesAsync(provider, connectionstring, sqlString, parameters);
        }
        
        public PCSYS_PPG_LPS_ProxyConnector.DataService.ServerInfo GetScriptDatabase() {
            return base.Channel.GetScriptDatabase();
        }
        
        public System.Threading.Tasks.Task<PCSYS_PPG_LPS_ProxyConnector.DataService.ServerInfo> GetScriptDatabaseAsync() {
            return base.Channel.GetScriptDatabaseAsync();
        }
        
        public System.Data.DataSet GetSchemas() {
            return base.Channel.GetSchemas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSchemasAsync() {
            return base.Channel.GetSchemasAsync();
        }
        
        public string GetCurrentDatabaseInfo() {
            return base.Channel.GetCurrentDatabaseInfo();
        }
        
        public System.Threading.Tasks.Task<string> GetCurrentDatabaseInfoAsync() {
            return base.Channel.GetCurrentDatabaseInfoAsync();
        }
        
        public bool TestExternalConnection(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionString) {
            return base.Channel.TestExternalConnection(provider, connectionString);
        }
        
        public System.Threading.Tasks.Task<bool> TestExternalConnectionAsync(PCSYS_PPG_LPS_ProxyConnector.DataService.DataProvider provider, string connectionString) {
            return base.Channel.TestExternalConnectionAsync(provider, connectionString);
        }
        
        public PCSYS_PPG_LPS_ProxyConnector.DataService.IndexOptimizationSuggestion[] GetIndexOptimizationSuggestions() {
            return base.Channel.GetIndexOptimizationSuggestions();
        }
        
        public System.Threading.Tasks.Task<PCSYS_PPG_LPS_ProxyConnector.DataService.IndexOptimizationSuggestion[]> GetIndexOptimizationSuggestionsAsync() {
            return base.Channel.GetIndexOptimizationSuggestionsAsync();
        }
    }
}
